const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('rainyDesktop', {
  minimize: () => ipcRenderer.invoke('window:minimize'),
  close: () => ipcRenderer.invoke('window:close'),
  toggleChat: () => ipcRenderer.invoke('window:toggle-chat'),
  toggleAlwaysOnTop: () => ipcRenderer.invoke('window:toggle-always-on-top'),
  getWindowPosition: () => ipcRenderer.invoke('window:get-position'),
  setWindowPosition: (position) => ipcRenderer.invoke('window:set-position', position),
  speakOnAvatar: (payload) => ipcRenderer.invoke('avatar:speak', payload),
  updateAvatarSettings: (settings) => ipcRenderer.invoke('avatar:update-settings', settings),
  setAvatarState: (state) => ipcRenderer.invoke('avatar:set-state', state),
  listAvatarModels: () => ipcRenderer.invoke('avatar:list-models'),
  uploadAvatarModel: () => ipcRenderer.invoke('avatar:upload-model'),
  deleteAvatarModel: (model) => ipcRenderer.invoke('avatar:delete-model', model),
  getCurrentAvatarModel: () => ipcRenderer.invoke('avatar:get-model'),
  setCurrentAvatarModel: (model) => ipcRenderer.invoke('avatar:set-model', model),
  notifyWakewordTriggered: () => ipcRenderer.invoke('avatar:wakeword-triggered'),
  notifyAvatarSpeechStatus: (payload) => ipcRenderer.invoke('avatar:speech-status', payload),
  executeAction: (action) => ipcRenderer.invoke('system:execute-action', action),
  openChatSession: (sessionId) => ipcRenderer.invoke('chat:open-session', sessionId),
  onToggleVoice: (callback) => ipcRenderer.on('rainy:toggle-voice', callback),
  onAvatarSpeak: (callback) => ipcRenderer.on('rainy:avatar-speak', (_event, payload) => callback(payload)),
  onAvatarSettings: (callback) => ipcRenderer.on('rainy:avatar-settings', (_event, settings) => callback(settings)),
  onAvatarState: (callback) => ipcRenderer.on('rainy:avatar-state', (_event, state) => callback(state)),
  onAvatarWakewordTriggered: (callback) => ipcRenderer.on('rainy:avatar-wakeword-triggered', (_event, payload) => callback(payload)),
  onAvatarModel: (callback) => ipcRenderer.on('rainy:avatar-model', (_event, payload) => callback(payload)),
  onAvatarSpeechStatus: (callback) => ipcRenderer.on('rainy:avatar-speech-status', (_event, payload) => callback(payload)),
  onSpotifyPlayback: (callback) => ipcRenderer.on('rainy:spotify-playback', (_event, payload) => callback(payload)),
  onSpotifyTrackChanged: (callback) => ipcRenderer.on('rainy:spotify-track-changed', () => callback()),
  onGlobalCursor: (callback) => ipcRenderer.on('rainy:global-cursor', (_event, payload) => callback(payload)),
  onOpenChatSession: (callback) => ipcRenderer.on('rainy:open-chat-session', (_event, sessionId) => callback(sessionId)),
  openSettingsWindow: () => ipcRenderer.invoke('window:open-settings'),
  openSetupWindow: () => ipcRenderer.invoke('window:open-setup'),
  getProfile: () => ipcRenderer.invoke('profile:get'),
  saveProfile: (profile) => ipcRenderer.invoke('profile:save', profile),
  patchProfile: (patch) => ipcRenderer.invoke('profile:patch', patch),
  updateTheme: (isDark) => ipcRenderer.invoke('settings:update-theme', isDark),
  onThemeUpdate: (callback) => ipcRenderer.on('rainy:theme-update', (_event, isDark) => callback(isDark)),
  onProfileUpdate: (callback) => ipcRenderer.on('rainy:profile-update', (_event, profile) => callback(profile)),
  getMicDevice: () => ipcRenderer.invoke('audio:get-mic-device'),
  setMicDevice: (deviceId) => ipcRenderer.invoke('audio:set-mic-device', deviceId),
  getTtsPreferences: () => ipcRenderer.invoke('tts:get-preferences'),
  setTtsPreferences: (prefs) => ipcRenderer.invoke('tts:set-preferences', prefs),
  getDiscordPreferences: () => ipcRenderer.invoke('discord:get-preferences'),
  setDiscordPreferences: (prefs) => ipcRenderer.invoke('discord:set-preferences', prefs),
});
